api_accounts_bookings_collection:
    pattern:  /
    defaults: { _controller: WalletApiBundle:Account:getBookings }
    methods: [GET]
    
#api_bookings_create:
#    pattern:  /
#    defaults: { _controller: WalletApiBundle:Booking:create }
#    methods: [POST]
#
#api_bookings_object:
#    pattern:  /{bookingId}
#    defaults: { _controller: WalletApiBundle:Booking:object }
#    methods: [GET]
#    
#api_bookings_update:
#    pattern:  /{bookingId}
#    defaults: { _controller: WalletApiBundle:Booking:update }
#    methods: [PUT]
#    
#api_bookings_delete:
#    pattern:  /{bookingId}
#    defaults: { _controller: WalletApiBundle:Booking:delete }
#    methods: [DELETE]
