frontend_index:
    pattern:  /
    defaults: { _controller: WalletFrontendBundle:Page:index }

frontend_dashboard:
    pattern:  /dashboard
    defaults: { _controller: WalletFrontendBundle:Page:dashboard }
