wallet_desktop_frontend:
    resource: "@WalletDesktopFrontendBundle/Resources/config/routing.yml"
    prefix:   /

wallet_api:
    resource: "@WalletApiBundle/Resources/config/routing.yml"
    prefix:   /api

