services:
    wallet.account_balance_aggregator:
        class: Wallet\DataBundle\Service\AccountBalanceAggregator
        arguments:
            - @doctrine
    wallet.twig.account_extension:
        class: Wallet\DataBundle\Twig\AccountExtension
        arguments:
            - @wallet.account_balance_aggregator
        tags:
            - { name: twig.extension }
    wallet.user.user_creation:
        class: Wallet\UserBundle\EventListener\UserCreationListener
        arguments: 
            - @doctrine
            - @service_container
        tags:
            - { name: kernel.event_subscriber }
