services:
    kernel.listener.fronted_chooser:
        class: Wallet\FrontendBundle\Listener\FrontendChooserListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
