index:
    pattern: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: dashboard, permanent: true }

dashboard:
    pattern:  /dashboard
    defaults: { _controller: WalletDesktopFrontendBundle:Page:dashboard }
