parameters:
#    wallet_data.example.class: Wallet\DataBundle\Example

services:
#    wallet_data.example:
#        class: %wallet_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
